# Generated by Django 3.0.5 on 2021-08-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
